### ISSUE TITLE
Uncaught IllegalStateException

### ISSUE THREAD

**Issue by ptrbrynt** [JesusM/FingerprintManager#12]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
       at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:205)
       at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:171)
       at com.jesusm.kfingerprintmanager.base.ui.FingerprintBaseDialogFragment.close(FingerprintBaseDialogFragment.kt:92)
       at com.jesusm.kfingerprintmanager.base.ui.presenter.FingerprintBaseDialogPresenter.close(FingerprintBaseDialogPresenter.kt:27)
       at com.jesusm.kfingerprintmanager.authentication.presenter.FingerprintAuthenticationDialogPresenter.onAuthenticationSucceeded(FingerprintAuthenticationDialogPresenter.kt:73)
       at android.support.v4.hardware.fingerprint.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1.onAuthenticationSucceeded(FingerprintManagerCompat.java:302)
       at android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1.onAuthenticationSucceeded(FingerprintManagerCompatApi23.java:122)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:922)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:846)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

**Comment by ptrbrynt** [comment]
Can this be looked into please? 😀

**Comment by JesusM** [comment]
@ptrbrynt Hi! Checking the stacktrace, it seems that the dialog is being closed after your activity is destroyed. Could you provide some steps to reproduce the issue? That would allow me to better understand the issue. 
Thanks

**Comment by ptrbrynt** [comment]
@JesusM I haven't actually been able to reproduce this myself I'm afraid - it's just being reported through Crashlytics by my users. I've put a try/catch block at every possible point of failure (i.e. around the `authenticate()` call, and inside each callback method) but still crashing I'm afraid. I also only call `authenticate()` if `getApplicationContext() != null && !isFinishing()`. Hope that helps!

**Comment by JesusM** [comment]
@ptrbrynt When is the fingerprint manager launched? Is there any particular event being raised after being launched? Could the host activity be in the background while the dialog is being displayed? Is there any particular pattern from the crashes you've seen? That would also help to know if it could being done in a "risky" moment. I recommend reading http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html to better understand the problem and to have some tips about when that happens.

I could use `commitAllowingStateLoss()` but I'd prefer to do it as last resort.

**Comment by ptrbrynt** [comment]
Ah, I've just realised what the issue probably is - I'm calling an asynchronous API call which finishes the activity inside the `AuthenticationCallback` methods. I guess the reason I can't replicate it is because it's asynchronous, so it's pretty uncommon but sometimes happens quickly enough to cause the crash. Is there a recommended way of doing this so that it doesn't crash?

**Comment by JesusM** [comment]
I've been trying to reproduce the case you're describing without any luck. I've used this patch:
```
Index: sample/src/main/java/jesusm/com/fingerprintmanager/sample/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sample/src/main/java/jesusm/com/fingerprintmanager/sample/MainActivity.kt	(date 1507097026000)
+++ sample/src/main/java/jesusm/com/fingerprintmanager/sample/MainActivity.kt	(revision )
@@ -1,5 +1,6 @@
 package jesusm.com.fingerprintmanager.sample
 
+import android.os.AsyncTask
 import android.os.Bundle
 import android.support.annotation.StyleRes
 import android.support.v7.app.AppCompatActivity
@@ -57,7 +58,17 @@
                 }
 
                 override fun onAuthenticationSuccess() {
-                    messageTextView.value.text = "Successfully authenticated"
+                    object : AsyncTask<Void, Void, Void?>() {
+                        override fun doInBackground(vararg params: Void): Void? {
+                            Thread.sleep(1)
+                            return null
+                        }
+
+                        override fun onPostExecute(result: Void?) {
+//                            messageTextView.value.text = "Successfully authenticated"
+                            finish()
+                        }
+                    }.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)
                 }
 
                 override fun onSuccessWithManualPassword(password: String) {
```

which simulates a very fast async task which finishes the activity on its `onPostResult`. Is that similar to your use of the asynchronous call?

I guess I could force to always close the dialog before any return call is triggered and I could use `dismissAllowingStateLoss()` rather than `dismiss()`. Do you mind if I push a new branch with those changes in order to let you use it and tell me if it works for you?

**Comment by ptrbrynt** [comment]
That sounds great, thanks!

**Comment by JesusM** [comment]
@ptrbrynt I've created #14 in order to prevent the crash, could you check it out and see if it works for you?

**Comment by boris01** [comment]
Hi JesusM,
Did you push this fix to the https://jitpack.io?
